server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tracelog}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 25MB
      max-request-size: 30MB
      file-size-threshold: 0B

  devtools:
    restart:
      enabled: true
app:
  storage:
    image-dir: ${IMAGE_DIR:storage/images}
    public-url-prefix: ${IMAGE_URL_PREFIX:/img}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: info
    org.springframework.web: debug
    org.springframework.security: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
